version: '3.9'

volumes:
  pgdata:

networks:
  private:

services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - private

  web:
    image: 97wave/dz5_CI-CD:latest
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./media:/app/media

    networks:
      - private

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/django/static:root
      - ./media:/var/www/django/media:root
    depends_on:
      - web
    # ports:
    #   - 80:80
    networks:
      - private